apiVersion: v1
kind: Pod
metadata:
  name: init-container-err
spec:
  initContainers:
  - name: init-1
    image: busybox
    command: ["sh", "-c", "echo Hello from the init container > /work-dir/index.html"]
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  - name: init-2
    image: busybox
    command: ["sh", "-c", "err"]
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    emptyDir: {}