apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-ds
  labels:
    app: busybox-ds
spec:
  selector:
    matchLabels:
      app: busybox-ds
  template:
    metadata:
      labels:
        app: busybox-ds
    spec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchFields:
            - key: metadata.name
              operator: In
              values:
              - k8s-n2
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - "while :; do cat echo "Hello world!!"; sleep 1; done"
