kind: Service
apiVersion: v1
metadata:
  name: the-service
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  externalIPs: ["172.22.132.99"]
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080
