apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns
  name: coredns-tcp
  namespace: external-dns
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.99.100
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
  selector:
    k8s-app: coredns
