apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
spec:
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: ampq
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: node
      port: 25672
      targetPort: 25672
  selector:
    app: rabbitmq
  type: ClusterIP
  clusterIP: None
