apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
      protocol: TCP
    - name: ampq
      port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app: rabbitmq
  type: ClusterIP
